### ISSUE TITLE
base_url in different Behat profiles not respected

### ISSUE THREAD

**Issue by lnhrdt** [shvetsgroup/ParallelRunner#14]
With a behat.yml configuration file such as the one below, when running `profile_a` the base_url is not used -- the tests run on `URL_A`.

```
default:
    extensions:
        page_object_extension.phar: ~
        Behat\MinkExtension\Extension:
            goutte: ~
            selenium2: ~
            base_url: URL_A
            default_session: selenium2
            browser_name: 'firefox'
        shvetsgroup\ParallelRunner\Extension: ~
profile_a:
    extensions:
        Behat\MinkExtension\Extension:
            base_url: URL_B
            browser_name: 'firefox'
        shvetsgroup\ParallelRunner\Extension:
            process_count: 4
```
