### ISSUE TITLE
cannot load ParallelRunner extension outside of default Behat profile

### ISSUE THREAD

**Issue by lnhrdt** [shvetsgroup/ParallelRunner#15]
ParallelRunner appears to not load when instantiated in a Behat profile besides `default`. In a Behat configuration profile such as the one below, ParallelRunner does not operate and Behat executes tests normally in one process.

```
default:
profile_a:
    extensions:
        Behat\MinkExtension\Extension:
            base_url: URL_A
            browser_name: 'firefox'
        shvetsgroup\ParallelRunner\Extension:
            process_count: 4
```
