### ISSUE TITLE
ParallelRunner not loading due to autoloader/Extension error??

### ISSUE THREAD

**Issue by jetyliu727** [shvetsgroup/ParallelRunner#25]
composer.json

```
{
    "require": {
        "behat/behat": ">=2.4.6,<3.0",
        "behat/mink": "1.4.*@stable",
        "behat/mink-goutte-driver": "*",
        "behat/mink-extension": "*",
        "behat/mink-selenium2-driver": "*",
        "shvetsgroup/parallelrunner": "dev-master"
    }
}
```

behat.yml

```
default:
  paths:
    features: features
    bootstrap: %behat.paths.features%/boostrap
  extensions:
    shvetsgroup\ParallelRunner\Extension:
      process_count: 2
    Behat\MinkExtension\Extension:
      goutte: ~
      selenium2:
        wd_host: http://127.0.0.1:4444/wd/hub
        browser: 'firefox'
        capabilities:
          version: '' # required
quick:
  filters:
    tags: '@testA,@testB'
```

What I expect/hope to happen is two browsers will launch with one running tests in @testA another running tests in @testB

```
behat --profile quick
```

However, the above doesn't work, with error

```
PHP Warning:  require(shvetsgroup\ParallelRunner\Extension): failed to open stream: No such file or directory in /home/User/vendor/behat/behat/src/Behat/Behat/Extension/ExtensionManager.php on line 112
PHP Fatal error:  require(): Failed opening required 'shvetsgroup\ParallelRunner\Extension' (include_path='.:/home/User/sourcesvn/common:/usr/share/php:/home/User/minkSelenium/vendor/behat/shvetsgroup/parallelrunner/src') in /home/User/vendor/behat/behat/src/Behat/Behat/Extension/ExtensionManager.php on line 112
```

My directory structure looks like

```
/home/User/minkSelenium/
/home/User/minkSelenium/vendor/behat
/home/User/minkSelenium/vendor/behat/behat
/home/User/minkSelenium/vendor/behat/mink-extension
/home/User/minkSelenium/vendor/behat/mink-selenium2-driver
/home/User/minkSelenium/vendor/behat/shvetsgroup
...
```

Any help is much appreciated!
