### ISSUE TITLE
Not detecting all my features

### ISSUE THREAD

**Issue by David-Guillot** [shvetsgroup/ParallelRunner#29]
Hi,

I'm trying to use this parallel runner for one of my Sf2 bundles. I have 9 Behat features (some of them being very complex and needing lots of fixtures) so running Behat on the standard mode with Symfony2 Extension takes more than an hour (XDebug is on). So, I tried to configure this parallel runner by doing :

``` yml
default:
  extensions:
    shvetsgroup\ParallelRunner\Extension:
      process_count: 2
      profiles:
        - stats

stats:
  filters:
    tags: "@stats"
  extensions:
    Behat\Symfony2Extension\Extension:
      kernel:
        env: test_stats
        debug: false
        path: Tests/Fixtures/Project/app/AppKernel.php
        bootstrap: Tests/Fixtures/Project/app/bootstrap.php
```

This way I'm trying to isolate the most greedy Behat feature (some complex stats computing) and let my 8 other features be ran by the default profile. Of course, having a Doctrine database, I had to set a specific Symfony environment.

Anyway ; Behat launches, but it doesn't want to run all my features. Sometimes 6 of them are ran, sometimes 3 of them... I didn't manage to determine a pattern or a reason of that :(

Would you have an idea ?
