### ISSUE TITLE
Profiles config error

### ISSUE THREAD

**Issue by ghost** [shvetsgroup/ParallelRunner#35]
Hello,

when i add this config:

```
default:
    extensions:
        shvetsgroup\ParallelRunner\Extension:
            profiles:
                - p1
                - p2
```

i got the error message: 
```
[Symfony\Component\Config\Definition\Exception\InvalidTypeException]
Invalid type for path "testwork.ParallelRunner.profiles". Expected scalar, but got array.
```

What i am doing wrong? I use Behat 3.4.3.
